-- Seshhon database setup. Paste this whole file into the Supabase SQL editor and press Run.
-- Run it once on a new project. (Generated by tools/live/build-setup.sh from supabase/migrations and supabase/examples.sql.)

-- ======================= 0001_init.sql
-- Seshhon database, first version.
-- Run this once in a new Supabase project (SQL editor, or `supabase db push`).
-- It creates the tables, the access rules (who can see and change what),
-- and the functions the app calls for status, deal codes and locking a sesh.

-- ---------------------------------------------------------------- types
create type public.status_colour as enum ('on', 'thinking', 'off');
create type public.friendship_state as enum ('requested', 'accepted', 'blocked');
create type public.deal_type as enum ('Food', 'Drinks', 'Entry', 'Events');

-- ---------------------------------------------------------------- tables
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null check (char_length(name) between 1 and 24),
  -- Sign-up is refused unless the person confirms they are 18 or over.
  adult_confirmed_at timestamptz not null,
  push_token text,
  created_at timestamptz not null default now()
);

create table public.friendships (
  id uuid primary key default gen_random_uuid(),
  requester uuid not null references public.profiles (id) on delete cascade,
  addressee uuid not null references public.profiles (id) on delete cascade,
  state public.friendship_state not null default 'requested',
  created_at timestamptz not null default now(),
  check (requester <> addressee)
);
-- One row per pair of people, whoever asked first.
create unique index friendships_pair on public.friendships (least(requester, addressee), greatest(requester, addressee));

create table public.statuses (
  user_id uuid primary key references public.profiles (id) on delete cascade,
  colour public.status_colour not null default 'off',
  expires_at timestamptz,
  updated_at timestamptz not null default now()
);

create table public.venues (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  kind text,
  lat double precision,
  lng double precision,
  closes text,
  places_id text
);

-- People who may enter deals and confirm codes for a venue.
create table public.venue_staff (
  venue_id uuid not null references public.venues (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  primary key (venue_id, user_id)
);

create table public.deals (
  id uuid primary key default gen_random_uuid(),
  venue_id uuid not null references public.venues (id) on delete cascade,
  type public.deal_type not null,
  title text not null check (char_length(title) between 3 and 80),
  start_time time not null,
  end_time time not null,
  is_alcohol boolean not null default false,
  discount_pct integer check (discount_pct between 0 and 100),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  check (end_time > start_time),
  -- Limits from the WA policy on responsible promotion of liquor, applied to
  -- every alcohol deal: at most 50% off, at most 60 minutes, finished by 7pm.
  -- Have a liquor lawyer confirm these before changing them.
  constraint alcohol_discount_limit check (not is_alcohol or coalesce(discount_pct, 0) <= 50),
  constraint alcohol_length_limit check (not is_alcohol or end_time - start_time <= interval '60 minutes'),
  constraint alcohol_ends_by_7pm check (not is_alcohol or end_time <= time '19:00')
);

create table public.seshes (
  id uuid primary key default gen_random_uuid(),
  creator uuid not null references public.profiles (id) on delete cascade,
  locked_venue uuid references public.venues (id),
  created_at timestamptz not null default now(),
  ended_at timestamptz
);

create table public.sesh_members (
  sesh_id uuid not null references public.seshes (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (sesh_id, user_id)
);

create table public.venue_votes (
  sesh_id uuid not null references public.seshes (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  venue_id uuid not null references public.venues (id) on delete cascade,
  voted_at timestamptz not null default now(),
  primary key (sesh_id, user_id)
);

create table public.redemptions (
  id uuid primary key default gen_random_uuid(),
  deal_id uuid not null references public.deals (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  code text not null,
  -- The night the code belongs to. A night runs until 5am, so 1am counts as the night before.
  night date not null,
  expires_at timestamptz not null,
  confirmed_at timestamptz,
  confirmed_by uuid references public.profiles (id),
  -- One use per person, per deal, per night.
  unique (deal_id, user_id, night)
);

create table public.ratings (
  venue_id uuid not null references public.venues (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  stars integer not null check (stars between 1 and 5),
  tags text[] not null default '{}',
  updated_at timestamptz not null default now(),
  primary key (venue_id, user_id)
);

-- ---------------------------------------------------------------- helpers
-- These run with the table owner's rights so access rules can call them
-- without the rules checking themselves in a loop.

create function public.are_friends(a uuid, b uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.friendships f
    where f.state = 'accepted'
      and ((f.requester = a and f.addressee = b) or (f.requester = b and f.addressee = a))
  );
$$;

create function public.is_sesh_member(s uuid, u uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.sesh_members m where m.sesh_id = s and m.user_id = u);
$$;

create function public.sesh_creator(s uuid) returns uuid
language sql stable security definer set search_path = public as $$
  select creator from public.seshes where id = s;
$$;

create function public.is_venue_staff(v uuid, u uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.venue_staff vs where vs.venue_id = v and vs.user_id = u);
$$;

-- The pilot runs in Perth, so deal hours and "tonight" use Perth time.
create function public.local_now(at timestamptz default now()) returns timestamp
language sql stable as $$ select at at time zone 'Australia/Perth'; $$;

create function public.night_of(at timestamptz default now()) returns date
language sql stable as $$ select (public.local_now(at) - interval '5 hours')::date; $$;

create function public.deal_is_running(d public.deals, at timestamptz default now()) returns boolean
language sql stable as $$
  select d.active and public.local_now(at)::time >= d.start_time and public.local_now(at)::time < d.end_time;
$$;

-- A venue can run at most two alcohol deals at a time.
create function public.check_alcohol_deal_count() returns trigger
language plpgsql as $$
begin
  if new.is_alcohol and new.active and (
    select count(*) from public.deals d
    where d.venue_id = new.venue_id and d.is_alcohol and d.active and d.id <> new.id
  ) >= 2 then
    raise exception 'A venue can run at most two alcohol deals per day.';
  end if;
  return new;
end;
$$;
create trigger deals_alcohol_count before insert or update on public.deals
  for each row execute function public.check_alcohol_deal_count();

-- ---------------------------------------------------------------- functions the app calls

-- Set your status. On lasts 4 hours, Thinking 2 hours, Off has no end.
create function public.set_status(new_colour public.status_colour) returns public.statuses
language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  result public.statuses;
begin
  if me is null then raise exception 'Sign in first.'; end if;
  insert into public.statuses (user_id, colour, expires_at, updated_at)
  values (
    me, new_colour,
    case new_colour when 'on' then now() + interval '4 hours' when 'thinking' then now() + interval '2 hours' else null end,
    now()
  )
  on conflict (user_id) do update
    set colour = excluded.colour, expires_at = excluded.expires_at, updated_at = excluded.updated_at
  returning * into result;
  return result;
end;
$$;

-- Turn expired statuses Off. Scheduled every five minutes at the end of this file.
create function public.expire_statuses() returns integer
language plpgsql security definer set search_path = public as $$
declare n integer;
begin
  update public.statuses set colour = 'off', expires_at = null, updated_at = now()
  where colour <> 'off' and expires_at <= now();
  get diagnostics n = row_count;
  return n;
end;
$$;

-- Get a code for a deal. Fails if the deal is not running or you used it tonight.
create function public.request_deal_code(p_deal uuid) returns public.redemptions
language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  d public.deals;
  r public.redemptions;
  tonight date := public.night_of();
  fresh text := 'SESH-' || (1000 + floor(random() * 9000))::int;
begin
  if me is null then raise exception 'Sign in first.'; end if;
  select * into d from public.deals where id = p_deal;
  if not found then raise exception 'That deal does not exist.'; end if;
  if not public.deal_is_running(d) then raise exception 'That deal is not running right now.'; end if;

  select * into r from public.redemptions where deal_id = p_deal and user_id = me and night = tonight;
  if found and r.confirmed_at is not null then
    raise exception 'You have already used this deal tonight.';
  end if;
  if found and r.expires_at > now() then
    return r; -- the code you already have is still good
  end if;

  insert into public.redemptions (deal_id, user_id, code, night, expires_at)
  values (p_deal, me, fresh, tonight, now() + interval '15 minutes')
  on conflict (deal_id, user_id, night) do update
    set code = excluded.code, expires_at = excluded.expires_at
  returning * into r;
  return r;
end;
$$;

-- Venue staff confirm a code. Works once, only for their own venue, only before it runs out.
create function public.confirm_deal_code(p_code text) returns public.redemptions
language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  r public.redemptions;
begin
  if me is null then raise exception 'Sign in first.'; end if;
  select red.* into r
  from public.redemptions red
  join public.deals d on d.id = red.deal_id
  where red.code = p_code and red.night = public.night_of() and public.is_venue_staff(d.venue_id, me)
  order by red.expires_at desc
  limit 1;
  if not found then raise exception 'That code is not valid at your venue tonight.'; end if;
  if r.confirmed_at is not null then raise exception 'That code has already been used.'; end if;
  if r.expires_at <= now() then raise exception 'That code has run out. Ask for a new one.'; end if;
  update public.redemptions set confirmed_at = now(), confirmed_by = me where id = r.id returning * into r;
  return r;
end;
$$;

-- Start a sesh. You must be On, and you join it straight away.
create function public.start_sesh() returns public.seshes
language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  s public.seshes;
begin
  if me is null then raise exception 'Sign in first.'; end if;
  if not exists (select 1 from public.statuses where user_id = me and colour = 'on' and expires_at > now()) then
    raise exception 'You need to be On to start a sesh.';
  end if;
  insert into public.seshes (creator) values (me) returning * into s;
  insert into public.sesh_members (sesh_id, user_id) values (s.id, me);
  return s;
end;
$$;

-- Lock in the venue with the most votes. Ties go to the venue that got its votes first.
create function public.lock_sesh(p_sesh uuid) returns public.seshes
language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  s public.seshes;
  winner uuid;
begin
  select * into s from public.seshes where id = p_sesh;
  if not found or s.creator <> me then raise exception 'Only the person who started the sesh can lock it in.'; end if;
  select venue_id into winner
  from public.venue_votes where sesh_id = p_sesh
  group by venue_id
  order by count(*) desc, min(voted_at) asc
  limit 1;
  if winner is null then raise exception 'Nobody has voted yet.'; end if;
  update public.seshes set locked_venue = winner where id = p_sesh returning * into s;
  return s;
end;
$$;

-- Average rating per venue.
create view public.venue_ratings with (security_invoker = true) as
  select venue_id, round(avg(stars)::numeric, 1) as average, count(*) as ratings
  from public.ratings group by venue_id;

-- ---------------------------------------------------------------- access rules
alter table public.profiles enable row level security;
alter table public.friendships enable row level security;
alter table public.statuses enable row level security;
alter table public.venues enable row level security;
alter table public.venue_staff enable row level security;
alter table public.deals enable row level security;
alter table public.seshes enable row level security;
alter table public.sesh_members enable row level security;
alter table public.venue_votes enable row level security;
alter table public.redemptions enable row level security;
alter table public.ratings enable row level security;

-- Profiles: you see yourself, your friends, and people with a pending request to or from you.
create policy profiles_read on public.profiles for select to authenticated using (
  id = auth.uid() or exists (
    select 1 from public.friendships f
    where f.state <> 'blocked'
      and ((f.requester = auth.uid() and f.addressee = profiles.id) or (f.addressee = auth.uid() and f.requester = profiles.id))
  )
);
create policy profiles_insert on public.profiles for insert to authenticated with check (id = auth.uid());
create policy profiles_update on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

-- Friendships: only the two people involved. Only the person asked can accept.
create policy friendships_read on public.friendships for select to authenticated
  using (requester = auth.uid() or addressee = auth.uid());
create policy friendships_request on public.friendships for insert to authenticated
  with check (requester = auth.uid() and state = 'requested');
create policy friendships_answer on public.friendships for update to authenticated
  using (addressee = auth.uid()) with check (addressee = auth.uid());
create policy friendships_remove on public.friendships for delete to authenticated
  using (requester = auth.uid() or addressee = auth.uid());

-- Statuses: you see your own. Friends see yours only while it is On or Thinking and not run out.
-- Changes go through set_status(), so there are no insert or update rules here.
create policy statuses_read on public.statuses for select to authenticated using (
  user_id = auth.uid()
  or (colour <> 'off' and expires_at > now() and public.are_friends(user_id, auth.uid()))
);

-- Venues and deals: any signed-in person can read. Venue staff manage their own deals.
create policy venues_read on public.venues for select to authenticated using (true);
create policy venue_staff_read on public.venue_staff for select to authenticated using (user_id = auth.uid());
create policy deals_read on public.deals for select to authenticated using (true);
create policy deals_insert on public.deals for insert to authenticated with check (public.is_venue_staff(venue_id, auth.uid()));
create policy deals_update on public.deals for update to authenticated
  using (public.is_venue_staff(venue_id, auth.uid())) with check (public.is_venue_staff(venue_id, auth.uid()));

-- Seshes: the creator, the members, and the creator's friends (so they can join).
create policy seshes_read on public.seshes for select to authenticated using (
  creator = auth.uid() or public.is_sesh_member(id, auth.uid()) or public.are_friends(creator, auth.uid())
);
create policy seshes_end on public.seshes for update to authenticated using (creator = auth.uid()) with check (creator = auth.uid());

create policy members_read on public.sesh_members for select to authenticated using (
  user_id = auth.uid() or public.is_sesh_member(sesh_id, auth.uid()) or public.are_friends(public.sesh_creator(sesh_id), auth.uid())
);
create policy members_join on public.sesh_members for insert to authenticated with check (
  user_id = auth.uid() and public.are_friends(public.sesh_creator(sesh_id), auth.uid())
);
create policy members_leave on public.sesh_members for delete to authenticated using (user_id = auth.uid());

-- Votes: members of the sesh see them; each member casts or changes only their own.
create policy votes_read on public.venue_votes for select to authenticated using (public.is_sesh_member(sesh_id, auth.uid()));
create policy votes_cast on public.venue_votes for insert to authenticated
  with check (user_id = auth.uid() and public.is_sesh_member(sesh_id, auth.uid()));
create policy votes_change on public.venue_votes for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid() and public.is_sesh_member(sesh_id, auth.uid()));
create policy votes_remove on public.venue_votes for delete to authenticated using (user_id = auth.uid());

-- Redemptions: you see your own. Codes are made and confirmed only through the functions above.
create policy redemptions_read on public.redemptions for select to authenticated using (user_id = auth.uid());

-- Ratings: anyone signed in can read; you write only your own.
create policy ratings_read on public.ratings for select to authenticated using (true);
create policy ratings_insert on public.ratings for insert to authenticated with check (user_id = auth.uid());
create policy ratings_update on public.ratings for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ---------------------------------------------------------------- permissions
grant usage on schema public to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert, delete on public.friendships to authenticated;
-- The person asked can change only the state (accept or block), not who the request is between.
grant update (state) on public.friendships to authenticated;
grant select on public.statuses, public.venues, public.venue_staff, public.redemptions, public.venue_ratings to authenticated;
grant select, insert, update on public.deals to authenticated;
grant select, update on public.seshes to authenticated;
grant select, insert, delete on public.sesh_members to authenticated;
grant select, insert, update, delete on public.venue_votes to authenticated;
grant select, insert, update on public.ratings to authenticated;

revoke execute on all functions in schema public from public;
grant execute on function
  public.are_friends(uuid, uuid), public.is_sesh_member(uuid, uuid), public.sesh_creator(uuid),
  public.is_venue_staff(uuid, uuid), public.local_now(timestamptz), public.night_of(timestamptz),
  public.deal_is_running(public.deals, timestamptz), public.set_status(public.status_colour),
  public.request_deal_code(uuid), public.confirm_deal_code(text), public.start_sesh(), public.lock_sesh(uuid)
to authenticated;

-- ---------------------------------------------------------------- schedule
-- Turn expired statuses Off every five minutes, if the pg_cron extension is switched on
-- (Supabase dashboard: Database, Extensions, pg_cron). Without it, expired statuses are
-- still hidden from friends by the access rule above; they just stay stored until changed.
do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('seshhon-expire-statuses', '*/5 * * * *', 'select public.expire_statuses()');
  end if;
end;
$$;

-- ======================= 0002_live_web_app.sql
-- Seshhon database, second step: everything the live web app needs.
-- Adds invite links, a single "give me everything" call for the app, and the
-- remaining actions (join, vote, end a sesh, rate, delete account).

-- ---------------------------------------------------------------- invite codes
-- Eight characters from an alphabet with no look-alikes (no I, L, O, 0 or 1).
create function public.new_invite_code() returns text
language sql volatile as $$
  select string_agg(substr('ABCDEFGHJKMNPQRSTUVWXYZ23456789', 1 + floor(random() * 31)::int, 1), '')
  from generate_series(1, 8);
$$;

alter table public.profiles add column invite_code text;
update public.profiles set invite_code = public.new_invite_code() where invite_code is null;
alter table public.profiles alter column invite_code set default public.new_invite_code();
alter table public.profiles alter column invite_code set not null;
alter table public.profiles add constraint profiles_invite_code_unique unique (invite_code);

-- Example venues are marked so the app can label them as examples.
alter table public.venues add column is_example boolean not null default false;

-- ---------------------------------------------------------------- tighter helpers
-- The helpers only answer questions about the person asking, so nobody can use
-- them to check on two other people.

create or replace function public.are_friends(a uuid, b uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select (auth.uid() = a or auth.uid() = b) and exists (
    select 1 from public.friendships f
    where f.state = 'accepted'
      and ((f.requester = a and f.addressee = b) or (f.requester = b and f.addressee = a))
  );
$$;

create or replace function public.is_sesh_member(s uuid, u uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select auth.uid() = u and exists (select 1 from public.sesh_members m where m.sesh_id = s and m.user_id = u);
$$;

create or replace function public.is_venue_staff(v uuid, u uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select auth.uid() = u and exists (select 1 from public.venue_staff vs where vs.venue_id = v and vs.user_id = u);
$$;

-- True when the person asking (b) is in a live sesh with a.
create function public.shares_sesh(a uuid, b uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select auth.uid() = b and exists (
    select 1
    from public.sesh_members m1
    join public.sesh_members m2 on m2.sesh_id = m1.sesh_id
    join public.seshes s on s.id = m1.sesh_id
    where m1.user_id = a and m2.user_id = b
      and s.ended_at is null and s.created_at > now() - interval '8 hours'
  );
$$;

-- True while the person asking is On or Thinking.
create function public.i_am_visible() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.statuses s
    where s.user_id = auth.uid() and s.colour <> 'off' and s.expires_at > now()
  );
$$;

-- Fair's fair: while you are Off you cannot see who else is On, or their seshes.
drop policy statuses_read on public.statuses;
create policy statuses_read on public.statuses for select to authenticated using (
  user_id = auth.uid()
  or (colour <> 'off' and expires_at > now() and public.are_friends(user_id, auth.uid()) and public.i_am_visible())
);

drop policy seshes_read on public.seshes;
create policy seshes_read on public.seshes for select to authenticated using (
  creator = auth.uid() or public.is_sesh_member(id, auth.uid())
  or (public.are_friends(creator, auth.uid()) and public.i_am_visible())
);

drop policy members_read on public.sesh_members;
create policy members_read on public.sesh_members for select to authenticated using (
  user_id = auth.uid() or public.is_sesh_member(sesh_id, auth.uid())
  or (public.are_friends(public.sesh_creator(sesh_id), auth.uid()) and public.i_am_visible())
);

-- People in the same live sesh can see each other's name.
create policy profiles_read_sesh on public.profiles for select to authenticated
  using (public.shares_sesh(id, auth.uid()));

-- The person who started a sesh can rejoin it after leaving.
drop policy members_join on public.sesh_members;
create policy members_join on public.sesh_members for insert to authenticated with check (
  user_id = auth.uid()
  and (public.sesh_creator(sesh_id) = auth.uid() or public.are_friends(public.sesh_creator(sesh_id), auth.uid()))
);

-- ---------------------------------------------------------------- sign-up and friends

create function public.api_sign_up(p_name text, p_adult boolean) returns jsonb
language plpgsql security invoker set search_path = public as $$
begin
  if auth.uid() is null then raise exception 'Sign in first.'; end if;
  if p_adult is not true then raise exception 'Seshhon is for people aged 18 and over.'; end if;
  if char_length(btrim(coalesce(p_name, ''))) not between 1 and 24 then
    raise exception 'Enter a first name of up to 24 characters.';
  end if;
  insert into public.profiles (id, name, adult_confirmed_at)
  values (auth.uid(), btrim(p_name), now())
  on conflict (id) do update set name = excluded.name;
  return '{}'::jsonb;
end;
$$;

-- Opening someone's invite link sends them a friend request. They still have to accept,
-- unless they had already asked you, in which case you are now friends.
create function public.request_friend(p_code text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  other public.profiles;
  f public.friendships;
begin
  if me is null then raise exception 'Sign in first.'; end if;
  if not exists (select 1 from public.profiles where id = me) then raise exception 'Finish signing up first.'; end if;
  select * into other from public.profiles where invite_code = upper(btrim(coalesce(p_code, '')));
  if not found then raise exception 'That invite link is not valid.'; end if;
  if other.id = me then raise exception 'That is your own invite link.'; end if;

  select * into f from public.friendships
  where (requester = me and addressee = other.id) or (requester = other.id and addressee = me);
  if found then
    if f.state = 'blocked' then raise exception 'That invite link is not valid.'; end if;
    if f.state = 'requested' and f.addressee = me then
      update public.friendships set state = 'accepted' where id = f.id;
      return jsonb_build_object('name', other.name, 'state', 'accepted');
    end if;
    return jsonb_build_object('name', other.name, 'state', f.state);
  end if;

  insert into public.friendships (requester, addressee) values (me, other.id);
  return jsonb_build_object('name', other.name, 'state', 'requested');
end;
$$;

-- Accept a request, or (with p_accept false) decline it, cancel it, or remove a friend.
create function public.answer_friend(p_friendship uuid, p_accept boolean) returns jsonb
language plpgsql security invoker set search_path = public as $$
begin
  if p_accept then
    update public.friendships set state = 'accepted'
    where id = p_friendship and addressee = auth.uid() and state = 'requested';
    if not found then raise exception 'That request is no longer there.'; end if;
  else
    delete from public.friendships
    where id = p_friendship and (requester = auth.uid() or addressee = auth.uid());
  end if;
  return '{}'::jsonb;
end;
$$;

-- ---------------------------------------------------------------- sesh actions

-- Starting a second sesh returns the one you already have running.
create or replace function public.start_sesh() returns public.seshes
language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  s public.seshes;
begin
  if me is null then raise exception 'Sign in first.'; end if;
  if not exists (select 1 from public.statuses where user_id = me and colour = 'on' and expires_at > now()) then
    raise exception 'You need to be On to start a sesh.';
  end if;
  select * into s from public.seshes
  where creator = me and ended_at is null and created_at > now() - interval '8 hours'
  order by created_at desc limit 1;
  if found then
    insert into public.sesh_members (sesh_id, user_id) values (s.id, me) on conflict do nothing;
    return s;
  end if;
  insert into public.seshes (creator) values (me) returning * into s;
  insert into public.sesh_members (sesh_id, user_id) values (s.id, me);
  return s;
end;
$$;

create function public.join_sesh(p_sesh uuid) returns jsonb
language plpgsql security invoker set search_path = public as $$
begin
  if not exists (
    select 1 from public.seshes
    where id = p_sesh and ended_at is null and created_at > now() - interval '8 hours'
  ) then
    raise exception 'That sesh has ended.';
  end if;
  insert into public.sesh_members (sesh_id, user_id) values (p_sesh, auth.uid()) on conflict do nothing;
  return '{}'::jsonb;
end;
$$;

create function public.leave_sesh(p_sesh uuid) returns jsonb
language plpgsql security invoker set search_path = public as $$
begin
  delete from public.venue_votes where sesh_id = p_sesh and user_id = auth.uid();
  delete from public.sesh_members where sesh_id = p_sesh and user_id = auth.uid();
  return '{}'::jsonb;
end;
$$;

-- Vote for a venue, change your vote, or (with p_venue null) take it back.
create function public.cast_vote(p_sesh uuid, p_venue uuid) returns jsonb
language plpgsql security invoker set search_path = public as $$
begin
  if not exists (
    select 1 from public.seshes
    where id = p_sesh and ended_at is null and locked_venue is null and created_at > now() - interval '8 hours'
  ) then
    raise exception 'Voting has closed for that sesh.';
  end if;
  if p_venue is null then
    delete from public.venue_votes where sesh_id = p_sesh and user_id = auth.uid();
  else
    insert into public.venue_votes (sesh_id, user_id, venue_id) values (p_sesh, auth.uid(), p_venue)
    on conflict (sesh_id, user_id) do update set venue_id = excluded.venue_id, voted_at = now();
  end if;
  return '{}'::jsonb;
end;
$$;

create function public.end_sesh(p_sesh uuid) returns jsonb
language plpgsql security invoker set search_path = public as $$
begin
  update public.seshes set ended_at = now() where id = p_sesh and creator = auth.uid();
  if not found then raise exception 'Only the person who started the sesh can end it.'; end if;
  return '{}'::jsonb;
end;
$$;

-- ---------------------------------------------------------------- ratings and account

create function public.rate_venue(p_venue uuid, p_stars integer, p_tags text[]) returns jsonb
language plpgsql security invoker set search_path = public as $$
declare
  tags text[] := coalesce(p_tags, '{}');
begin
  if coalesce(array_length(tags, 1), 0) > 5 or exists (select 1 from unnest(tags) t where char_length(t) > 24) then
    raise exception 'Too many tags.';
  end if;
  insert into public.ratings (venue_id, user_id, stars, tags, updated_at)
  values (p_venue, auth.uid(), p_stars, tags, now())
  on conflict (venue_id, user_id) do update set stars = excluded.stars, tags = excluded.tags, updated_at = now();
  return '{}'::jsonb;
end;
$$;

-- Removes the person's profile and everything attached to it.
create function public.delete_account() returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
begin
  if me is null then raise exception 'Sign in first.'; end if;
  delete from public.profiles where id = me;
  begin
    delete from auth.users where id = me;
  exception when insufficient_privilege then
    null; -- the sign-in record stays, but it no longer has any Seshhon data
  end;
  return '{}'::jsonb;
end;
$$;

-- ---------------------------------------------------------------- everything the app shows, in one call
-- Runs with the caller's own rights, so the access rules decide what comes back.
create function public.api_state() returns jsonb
language sql stable security invoker set search_path = public as $$
  select jsonb_build_object(
    'now', now(),
    'night', public.night_of(),
    'me', (
      select jsonb_build_object(
        'id', p.id, 'name', p.name, 'invite_code', p.invite_code,
        'colour', coalesce((select s.colour::text from public.statuses s where s.user_id = p.id and s.colour <> 'off' and s.expires_at > now()), 'off'),
        'expires_at', (select s.expires_at from public.statuses s where s.user_id = p.id and s.colour <> 'off' and s.expires_at > now())
      )
      from public.profiles p where p.id = auth.uid()
    ),
    'friends', coalesce((
      select jsonb_agg(
        jsonb_build_object('friendship', f.id, 'id', p.id, 'name', p.name, 'colour', coalesce(s.colour::text, 'off'), 'since', s.updated_at)
        order by case coalesce(s.colour::text, 'off') when 'on' then 0 when 'thinking' then 1 else 2 end, p.name
      )
      from public.friendships f
      join public.profiles p on p.id = case when f.requester = auth.uid() then f.addressee else f.requester end
      left join public.statuses s on s.user_id = p.id
      where f.state = 'accepted'
    ), '[]'::jsonb),
    'requests_in', coalesce((
      select jsonb_agg(jsonb_build_object('friendship', f.id, 'name', p.name) order by f.created_at)
      from public.friendships f join public.profiles p on p.id = f.requester
      where f.state = 'requested' and f.addressee = auth.uid()
    ), '[]'::jsonb),
    'requests_out', coalesce((
      select jsonb_agg(jsonb_build_object('friendship', f.id, 'name', p.name) order by f.created_at)
      from public.friendships f join public.profiles p on p.id = f.addressee
      where f.state = 'requested' and f.requester = auth.uid()
    ), '[]'::jsonb),
    'seshes', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', s.id,
          'mine', s.creator = auth.uid(),
          'creator_name', (select p.name from public.profiles p where p.id = s.creator),
          'locked_venue', s.locked_venue,
          'am_member', public.is_sesh_member(s.id, auth.uid()),
          'members', coalesce((
            select jsonb_agg(jsonb_build_object('id', m.user_id, 'name', p.name) order by m.joined_at)
            from public.sesh_members m left join public.profiles p on p.id = m.user_id
            where m.sesh_id = s.id
          ), '[]'::jsonb),
          'votes', coalesce((
            select jsonb_agg(jsonb_build_object('user_id', v.user_id, 'venue_id', v.venue_id, 'voted_at', v.voted_at))
            from public.venue_votes v where v.sesh_id = s.id
          ), '[]'::jsonb)
        )
        order by s.created_at desc
      )
      from public.seshes s
      where s.ended_at is null and s.created_at > now() - interval '8 hours'
    ), '[]'::jsonb),
    'venues', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', v.id, 'name', v.name, 'kind', v.kind, 'closes', v.closes, 'is_example', v.is_example,
          'average', (select r.average from public.venue_ratings r where r.venue_id = v.id),
          'ratings', coalesce((select r.ratings from public.venue_ratings r where r.venue_id = v.id), 0),
          'my_stars', coalesce((select r.stars from public.ratings r where r.venue_id = v.id and r.user_id = auth.uid()), 0),
          'my_tags', coalesce((select to_jsonb(r.tags) from public.ratings r where r.venue_id = v.id and r.user_id = auth.uid()), '[]'::jsonb)
        )
        order by v.name
      )
      from public.venues v
    ), '[]'::jsonb),
    'deals', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', d.id, 'venue_id', d.venue_id, 'type', d.type, 'title', d.title,
          'start_time', to_char(d.start_time, 'HH24:MI'), 'end_time', to_char(d.end_time, 'HH24:MI'),
          'running', public.deal_is_running(d),
          'used', coalesce(r.confirmed_at is not null, false),
          'code', case when r.confirmed_at is null and r.expires_at > now() then r.code end,
          'code_expires_at', case when r.confirmed_at is null and r.expires_at > now() then r.expires_at end
        )
        order by d.start_time, d.title
      )
      from public.deals d
      left join public.redemptions r on r.deal_id = d.id and r.user_id = auth.uid() and r.night = public.night_of()
      where d.active
    ), '[]'::jsonb),
    'staff_venues', coalesce((
      select jsonb_agg(vs.venue_id) from public.venue_staff vs where vs.user_id = auth.uid()
    ), '[]'::jsonb)
  );
$$;

-- ---------------------------------------------------------------- permissions
-- Supabase gives signed-out and signed-in visitors full rights on every new table and
-- function by default. Take all of that away, then hand back only what the app needs.
revoke all on all tables in schema public from public, anon, authenticated;
revoke execute on all functions in schema public from public, anon, authenticated;

-- Other people can read only your id, name and invite code, never your push token.
grant select (id, name, invite_code, created_at) on public.profiles to authenticated;
grant insert (id, name, adult_confirmed_at), update (name, push_token) on public.profiles to authenticated;
-- The person asked can change only the state (accept or block), not who the request is between.
grant select, insert, delete on public.friendships to authenticated;
grant update (state) on public.friendships to authenticated;
grant select on public.statuses, public.venues, public.venue_staff, public.redemptions, public.venue_ratings to authenticated;
grant select, insert, update on public.deals to authenticated;
grant select, update on public.seshes to authenticated;
grant select, insert, delete on public.sesh_members to authenticated;
grant select, insert, update, delete on public.venue_votes to authenticated;
grant select, insert, update on public.ratings to authenticated;

-- Signed-out visitors can call nothing. Signed-in people can call only what is listed.
grant execute on function
  public.are_friends(uuid, uuid), public.is_sesh_member(uuid, uuid), public.sesh_creator(uuid),
  public.is_venue_staff(uuid, uuid), public.shares_sesh(uuid, uuid), public.i_am_visible(), public.new_invite_code(),
  public.local_now(timestamptz), public.night_of(timestamptz), public.deal_is_running(public.deals, timestamptz),
  public.set_status(public.status_colour), public.request_deal_code(uuid), public.confirm_deal_code(text),
  public.start_sesh(), public.lock_sesh(uuid), public.join_sesh(uuid), public.leave_sesh(uuid),
  public.cast_vote(uuid, uuid), public.end_sesh(uuid), public.api_sign_up(text, boolean),
  public.request_friend(text), public.answer_friend(uuid, boolean), public.rate_venue(uuid, integer, text[]),
  public.delete_account(), public.api_state()
to authenticated;

-- ======================= 0003_age_gate.sql
-- Age gate: sign-up now asks for a date of birth and checks it on the server.
-- The date of birth is used for the check only. It is NOT stored; the database keeps
-- just the moment the person was confirmed as 18 or over.
-- Also lets the app label alcohol deals ("18+, ID required, drink responsibly").

drop function if exists public.api_sign_up(text, boolean);

create function public.api_sign_up(p_name text, p_birth_date date) returns jsonb
language plpgsql security invoker set search_path = public as $$
declare today date := (now() at time zone 'Australia/Perth')::date;
begin
  if auth.uid() is null then raise exception 'Sign in first.'; end if;
  if p_birth_date is null or p_birth_date > today or p_birth_date < date '1900-01-01' then
    raise exception 'Enter your date of birth.';
  end if;
  if p_birth_date > (today - interval '18 years')::date then
    raise exception 'Seshhon is for people aged 18 and over.';
  end if;
  if char_length(btrim(coalesce(p_name, ''))) not between 1 and 24 then
    raise exception 'Enter a first name of up to 24 characters.';
  end if;
  insert into public.profiles (id, name, adult_confirmed_at)
  values (auth.uid(), btrim(p_name), now())
  on conflict (id) do update set name = excluded.name;
  return '{}'::jsonb;
end;
$$;

revoke all on function public.api_sign_up(text, date) from public, anon, authenticated;
grant execute on function public.api_sign_up(text, date) to authenticated;

create or replace function public.api_state() returns jsonb
language sql stable security invoker set search_path = public as $$
  select jsonb_build_object(
    'now', now(),
    'night', public.night_of(),
    'me', (
      select jsonb_build_object(
        'id', p.id, 'name', p.name, 'invite_code', p.invite_code,
        'colour', coalesce((select s.colour::text from public.statuses s where s.user_id = p.id and s.colour <> 'off' and s.expires_at > now()), 'off'),
        'expires_at', (select s.expires_at from public.statuses s where s.user_id = p.id and s.colour <> 'off' and s.expires_at > now())
      )
      from public.profiles p where p.id = auth.uid()
    ),
    'friends', coalesce((
      select jsonb_agg(
        jsonb_build_object('friendship', f.id, 'id', p.id, 'name', p.name, 'colour', coalesce(s.colour::text, 'off'), 'since', s.updated_at)
        order by case coalesce(s.colour::text, 'off') when 'on' then 0 when 'thinking' then 1 else 2 end, p.name
      )
      from public.friendships f
      join public.profiles p on p.id = case when f.requester = auth.uid() then f.addressee else f.requester end
      left join public.statuses s on s.user_id = p.id
      where f.state = 'accepted'
    ), '[]'::jsonb),
    'requests_in', coalesce((
      select jsonb_agg(jsonb_build_object('friendship', f.id, 'name', p.name) order by f.created_at)
      from public.friendships f join public.profiles p on p.id = f.requester
      where f.state = 'requested' and f.addressee = auth.uid()
    ), '[]'::jsonb),
    'requests_out', coalesce((
      select jsonb_agg(jsonb_build_object('friendship', f.id, 'name', p.name) order by f.created_at)
      from public.friendships f join public.profiles p on p.id = f.addressee
      where f.state = 'requested' and f.requester = auth.uid()
    ), '[]'::jsonb),
    'seshes', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', s.id,
          'mine', s.creator = auth.uid(),
          'creator_name', (select p.name from public.profiles p where p.id = s.creator),
          'locked_venue', s.locked_venue,
          'am_member', public.is_sesh_member(s.id, auth.uid()),
          'members', coalesce((
            select jsonb_agg(jsonb_build_object('id', m.user_id, 'name', p.name) order by m.joined_at)
            from public.sesh_members m left join public.profiles p on p.id = m.user_id
            where m.sesh_id = s.id
          ), '[]'::jsonb),
          'votes', coalesce((
            select jsonb_agg(jsonb_build_object('user_id', v.user_id, 'venue_id', v.venue_id, 'voted_at', v.voted_at))
            from public.venue_votes v where v.sesh_id = s.id
          ), '[]'::jsonb)
        )
        order by s.created_at desc
      )
      from public.seshes s
      where s.ended_at is null and s.created_at > now() - interval '8 hours'
    ), '[]'::jsonb),
    'venues', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', v.id, 'name', v.name, 'kind', v.kind, 'closes', v.closes, 'is_example', v.is_example,
          'average', (select r.average from public.venue_ratings r where r.venue_id = v.id),
          'ratings', coalesce((select r.ratings from public.venue_ratings r where r.venue_id = v.id), 0),
          'my_stars', coalesce((select r.stars from public.ratings r where r.venue_id = v.id and r.user_id = auth.uid()), 0),
          'my_tags', coalesce((select to_jsonb(r.tags) from public.ratings r where r.venue_id = v.id and r.user_id = auth.uid()), '[]'::jsonb)
        )
        order by v.name
      )
      from public.venues v
    ), '[]'::jsonb),
    'deals', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', d.id, 'venue_id', d.venue_id, 'type', d.type, 'title', d.title, 'is_alcohol', d.is_alcohol,
          'start_time', to_char(d.start_time, 'HH24:MI'), 'end_time', to_char(d.end_time, 'HH24:MI'),
          'running', public.deal_is_running(d),
          'used', coalesce(r.confirmed_at is not null, false),
          'code', case when r.confirmed_at is null and r.expires_at > now() then r.code end,
          'code_expires_at', case when r.confirmed_at is null and r.expires_at > now() then r.expires_at end
        )
        order by d.start_time, d.title
      )
      from public.deals d
      left join public.redemptions r on r.deal_id = d.id and r.user_id = auth.uid() and r.night = public.night_of()
      where d.active
    ), '[]'::jsonb),
    'staff_venues', coalesce((
      select jsonb_agg(vs.venue_id) from public.venue_staff vs where vs.user_id = auth.uid()
    ), '[]'::jsonb)
  );
$$;

-- Ratings privacy: you can only read your own ratings (stars and tags). Everyone still
-- sees the venue totals and averages, which come from a view that only exposes aggregates.
alter view public.venue_ratings set (security_invoker = false);
drop policy if exists ratings_read on public.ratings;
create policy ratings_read on public.ratings for select to authenticated using (user_id = auth.uid());

-- ======================= examples.sql
-- Example venues and deals, so the app has something to show before real venues sign up.
-- None of these are real places. The app labels them "Example".
-- Safe to run more than once. To remove them later: delete from public.venues where is_example;

insert into public.venues (id, name, kind, closes, is_example) values
  ('a0000000-0000-4000-8000-000000000001', 'Lowtide Bar', 'Cocktail bar', 'open till 1am', true),
  ('a0000000-0000-4000-8000-000000000002', 'Bodega Nine', 'Pizza bar', 'open till 12am', true),
  ('a0000000-0000-4000-8000-000000000003', 'The Paper Lantern', 'Live music venue', 'open till 12am', true)
on conflict (id) do nothing;

insert into public.deals (id, venue_id, type, title, start_time, end_time, is_alcohol, discount_pct) values
  ('d0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'Food', 'Free share plate for groups of 4+', '17:00', '23:00', false, null),
  ('d0000000-0000-4000-8000-000000000002', 'a0000000-0000-4000-8000-000000000001', 'Drinks', 'Happy hour: 25% off house drinks', '17:00', '18:00', true, 25),
  ('d0000000-0000-4000-8000-000000000003', 'a0000000-0000-4000-8000-000000000002', 'Food', '2-for-1 pizzas', '17:00', '21:00', false, null),
  ('d0000000-0000-4000-8000-000000000004', 'a0000000-0000-4000-8000-000000000003', 'Entry', 'Free entry for groups of 4+', '20:00', '23:59:59', false, null),
  ('d0000000-0000-4000-8000-000000000005', 'a0000000-0000-4000-8000-000000000003', 'Events', 'Live music tonight, table held for your sesh', '19:00', '23:00', false, null),
  -- Runs all day so the deal code screen can be tried at any time.
  ('d0000000-0000-4000-8000-000000000006', 'a0000000-0000-4000-8000-000000000002', 'Food', 'Test deal: free garlic bread, any time', '00:00', '23:59:59', false, null)
on conflict (id) do nothing;
