-- Seshhon database update. Paste this whole file into the Supabase SQL editor and press Run.
-- Use it on a project that was set up before the age gate (sign up says it cannot find
-- public.api_sign_up(p_birth_date, p_name)). Run it once; do not use it on a new project, use setup.sql there.
-- (Generated by tools/live/build-setup.sh from supabase/migrations 0003 onwards.)

-- ======================= 0003_age_gate.sql
-- Age gate: sign-up now asks for a date of birth and checks it on the server.
-- The date of birth is used for the check only. It is NOT stored; the database keeps
-- just the moment the person was confirmed as 18 or over.
-- Also lets the app label alcohol deals ("18+, ID required, drink responsibly").

drop function if exists public.api_sign_up(text, boolean);

create function public.api_sign_up(p_name text, p_birth_date date) returns jsonb
language plpgsql security invoker set search_path = public as $$
declare today date := (now() at time zone 'Australia/Perth')::date;
begin
  if auth.uid() is null then raise exception 'Sign in first.'; end if;
  if p_birth_date is null or p_birth_date > today or p_birth_date < date '1900-01-01' then
    raise exception 'Enter your date of birth.';
  end if;
  if p_birth_date > (today - interval '18 years')::date then
    raise exception 'Seshhon is for people aged 18 and over.';
  end if;
  if char_length(btrim(coalesce(p_name, ''))) not between 1 and 24 then
    raise exception 'Enter a first name of up to 24 characters.';
  end if;
  insert into public.profiles (id, name, adult_confirmed_at)
  values (auth.uid(), btrim(p_name), now())
  on conflict (id) do update set name = excluded.name;
  return '{}'::jsonb;
end;
$$;

revoke all on function public.api_sign_up(text, date) from public, anon, authenticated;
grant execute on function public.api_sign_up(text, date) to authenticated;

create or replace function public.api_state() returns jsonb
language sql stable security invoker set search_path = public as $$
  select jsonb_build_object(
    'now', now(),
    'night', public.night_of(),
    'me', (
      select jsonb_build_object(
        'id', p.id, 'name', p.name, 'invite_code', p.invite_code,
        'colour', coalesce((select s.colour::text from public.statuses s where s.user_id = p.id and s.colour <> 'off' and s.expires_at > now()), 'off'),
        'expires_at', (select s.expires_at from public.statuses s where s.user_id = p.id and s.colour <> 'off' and s.expires_at > now())
      )
      from public.profiles p where p.id = auth.uid()
    ),
    'friends', coalesce((
      select jsonb_agg(
        jsonb_build_object('friendship', f.id, 'id', p.id, 'name', p.name, 'colour', coalesce(s.colour::text, 'off'), 'since', s.updated_at)
        order by case coalesce(s.colour::text, 'off') when 'on' then 0 when 'thinking' then 1 else 2 end, p.name
      )
      from public.friendships f
      join public.profiles p on p.id = case when f.requester = auth.uid() then f.addressee else f.requester end
      left join public.statuses s on s.user_id = p.id
      where f.state = 'accepted'
    ), '[]'::jsonb),
    'requests_in', coalesce((
      select jsonb_agg(jsonb_build_object('friendship', f.id, 'name', p.name) order by f.created_at)
      from public.friendships f join public.profiles p on p.id = f.requester
      where f.state = 'requested' and f.addressee = auth.uid()
    ), '[]'::jsonb),
    'requests_out', coalesce((
      select jsonb_agg(jsonb_build_object('friendship', f.id, 'name', p.name) order by f.created_at)
      from public.friendships f join public.profiles p on p.id = f.addressee
      where f.state = 'requested' and f.requester = auth.uid()
    ), '[]'::jsonb),
    'seshes', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', s.id,
          'mine', s.creator = auth.uid(),
          'creator_name', (select p.name from public.profiles p where p.id = s.creator),
          'locked_venue', s.locked_venue,
          'am_member', public.is_sesh_member(s.id, auth.uid()),
          'members', coalesce((
            select jsonb_agg(jsonb_build_object('id', m.user_id, 'name', p.name) order by m.joined_at)
            from public.sesh_members m left join public.profiles p on p.id = m.user_id
            where m.sesh_id = s.id
          ), '[]'::jsonb),
          'votes', coalesce((
            select jsonb_agg(jsonb_build_object('user_id', v.user_id, 'venue_id', v.venue_id, 'voted_at', v.voted_at))
            from public.venue_votes v where v.sesh_id = s.id
          ), '[]'::jsonb)
        )
        order by s.created_at desc
      )
      from public.seshes s
      where s.ended_at is null and s.created_at > now() - interval '8 hours'
    ), '[]'::jsonb),
    'venues', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', v.id, 'name', v.name, 'kind', v.kind, 'closes', v.closes, 'is_example', v.is_example,
          'average', (select r.average from public.venue_ratings r where r.venue_id = v.id),
          'ratings', coalesce((select r.ratings from public.venue_ratings r where r.venue_id = v.id), 0),
          'my_stars', coalesce((select r.stars from public.ratings r where r.venue_id = v.id and r.user_id = auth.uid()), 0),
          'my_tags', coalesce((select to_jsonb(r.tags) from public.ratings r where r.venue_id = v.id and r.user_id = auth.uid()), '[]'::jsonb)
        )
        order by v.name
      )
      from public.venues v
    ), '[]'::jsonb),
    'deals', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', d.id, 'venue_id', d.venue_id, 'type', d.type, 'title', d.title, 'is_alcohol', d.is_alcohol,
          'start_time', to_char(d.start_time, 'HH24:MI'), 'end_time', to_char(d.end_time, 'HH24:MI'),
          'running', public.deal_is_running(d),
          'used', coalesce(r.confirmed_at is not null, false),
          'code', case when r.confirmed_at is null and r.expires_at > now() then r.code end,
          'code_expires_at', case when r.confirmed_at is null and r.expires_at > now() then r.expires_at end
        )
        order by d.start_time, d.title
      )
      from public.deals d
      left join public.redemptions r on r.deal_id = d.id and r.user_id = auth.uid() and r.night = public.night_of()
      where d.active
    ), '[]'::jsonb),
    'staff_venues', coalesce((
      select jsonb_agg(vs.venue_id) from public.venue_staff vs where vs.user_id = auth.uid()
    ), '[]'::jsonb)
  );
$$;

-- Ratings privacy: you can only read your own ratings (stars and tags). Everyone still
-- sees the venue totals and averages, which come from a view that only exposes aggregates.
alter view public.venue_ratings set (security_invoker = false);
drop policy if exists ratings_read on public.ratings;
create policy ratings_read on public.ratings for select to authenticated using (user_id = auth.uid());

-- ======================= 0004_sesh_chat.sql
-- Sesh chat: short text messages between the people in a sesh. They are erased when the sesh
-- ends (or after 8 hours at the latest). Includes block and report.
-- Nobody reads or writes these tables directly: everything goes through the functions below.

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  sesh_id uuid not null references public.seshes (id) on delete cascade,
  sender uuid not null references public.profiles (id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);
create index messages_sesh_idx on public.messages (sesh_id, created_at);

create table public.blocks (
  blocker uuid not null references public.profiles (id) on delete cascade,
  blocked uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker, blocked),
  check (blocker <> blocked)
);

-- A report keeps a copy of the reported message so it can be looked at after the chat is erased.
-- Reports are deleted after 90 days. Only the project owner can read them (in the Supabase dashboard).
create table public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter uuid references public.profiles (id) on delete set null,
  reported uuid references public.profiles (id) on delete set null,
  sesh_id uuid,
  message_body text not null,
  reason text check (char_length(reason) <= 200),
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;
alter table public.blocks enable row level security;
alter table public.reports enable row level security;
revoke all on public.messages, public.blocks, public.reports from public, anon, authenticated;

-- ---------------------------------------------------------------- helpers

create function public.sesh_is_live(s uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.seshes where id = s and ended_at is null and created_at > now() - interval '8 hours');
$$;

create function public.blocked_between(a uuid, b uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.blocks where (blocker = a and blocked = b) or (blocker = b and blocked = a));
$$;

-- Deletes finished and old chats and old reports. Called by the functions below and, if the
-- pg_cron extension is on, every 5 minutes.
create function public.purge_chat() returns integer
language plpgsql security definer set search_path = public as $$
declare n integer;
begin
  delete from public.messages m
  where m.created_at < now() - interval '8 hours'
     or exists (select 1 from public.seshes s where s.id = m.sesh_id and (s.ended_at is not null or s.created_at < now() - interval '8 hours'));
  get diagnostics n = row_count;
  delete from public.reports where created_at < now() - interval '90 days';
  return n;
end;
$$;

-- ---------------------------------------------------------------- sending and reading

create function public.send_message(p_sesh uuid, p_body text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  body text := btrim(coalesce(p_body, ''));
begin
  if me is null then raise exception 'Sign in first.'; end if;
  if not public.is_sesh_member(p_sesh, me) or not public.sesh_is_live(p_sesh) then
    raise exception 'You can only chat in a sesh you are in.';
  end if;
  if char_length(body) = 0 then raise exception 'Type a message first.'; end if;
  if char_length(body) > 500 then raise exception 'Keep messages under 500 characters.'; end if;
  if (select count(*) from public.messages where sender = me and created_at > now() - interval '1 minute') >= 20 then
    raise exception 'Slow down a little.';
  end if;
  insert into public.messages (sesh_id, sender, body) values (p_sesh, me, body);
  if random() < 0.1 then perform public.purge_chat(); end if;
  return '{}'::jsonb;
end;
$$;

create function public.get_messages(p_sesh uuid) returns jsonb
language plpgsql volatile security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  out jsonb;
begin
  if me is null then raise exception 'Sign in first.'; end if;
  if not public.is_sesh_member(p_sesh, me) or not public.sesh_is_live(p_sesh) then
    return '[]'::jsonb;
  end if;
  if random() < 0.05 then perform public.purge_chat(); end if;
  select coalesce(jsonb_agg(x order by x_at), '[]'::jsonb) into out from (
    select jsonb_build_object('id', m.id, 'sender', m.sender, 'name', p.name, 'body', m.body, 'at', m.created_at) as x, m.created_at as x_at
    from public.messages m
    join public.profiles p on p.id = m.sender
    where m.sesh_id = p_sesh
      and (m.sender = me or not public.blocked_between(m.sender, me))
    order by m.created_at desc
    limit 200
  ) t;
  return out;
end;
$$;

-- ---------------------------------------------------------------- block and report

create function public.block_user(p_user uuid) returns jsonb
language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid();
begin
  if me is null then raise exception 'Sign in first.'; end if;
  if p_user is null or p_user = me or not exists (select 1 from public.profiles where id = p_user) then
    raise exception 'That person could not be blocked.';
  end if;
  insert into public.blocks (blocker, blocked) values (me, p_user) on conflict do nothing;
  -- Blocking also ends any friendship, so they stop seeing your status.
  delete from public.friendships
  where (requester = me and addressee = p_user) or (requester = p_user and addressee = me);
  insert into public.friendships (requester, addressee, state) values (me, p_user, 'blocked');
  return '{}'::jsonb;
end;
$$;

create function public.unblock_user(p_user uuid) returns jsonb
language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid();
begin
  if me is null then raise exception 'Sign in first.'; end if;
  delete from public.blocks where blocker = me and blocked = p_user;
  delete from public.friendships where requester = me and addressee = p_user and state = 'blocked';
  return '{}'::jsonb;
end;
$$;

create function public.blocked_list() returns jsonb
language sql stable security definer set search_path = public as $$
  select coalesce(jsonb_agg(jsonb_build_object('id', p.id, 'name', p.name) order by p.name), '[]'::jsonb)
  from public.blocks b join public.profiles p on p.id = b.blocked
  where b.blocker = auth.uid();
$$;

create function public.report_message(p_message uuid, p_reason text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  m public.messages;
begin
  if me is null then raise exception 'Sign in first.'; end if;
  select * into m from public.messages where id = p_message;
  if not found or not public.is_sesh_member(m.sesh_id, me) then raise exception 'That message is no longer there.'; end if;
  insert into public.reports (reporter, reported, sesh_id, message_body, reason)
  values (me, m.sender, m.sesh_id, m.body, left(coalesce(p_reason, ''), 200));
  return '{}'::jsonb;
end;
$$;

-- ---------------------------------------------------------------- ending a sesh erases its chat

create or replace function public.end_sesh(p_sesh uuid) returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  update public.seshes set ended_at = now() where id = p_sesh and creator = auth.uid();
  if not found then raise exception 'Only the person who started the sesh can end it.'; end if;
  delete from public.messages where sesh_id = p_sesh;
  return '{}'::jsonb;
end;
$$;

-- ---------------------------------------------------------------- permissions

revoke all on function
  public.sesh_is_live(uuid), public.blocked_between(uuid, uuid), public.purge_chat(),
  public.send_message(uuid, text), public.get_messages(uuid), public.block_user(uuid), public.unblock_user(uuid),
  public.blocked_list(), public.report_message(uuid, text)
from public, anon, authenticated;
grant execute on function
  public.send_message(uuid, text), public.get_messages(uuid), public.block_user(uuid), public.unblock_user(uuid),
  public.blocked_list(), public.report_message(uuid, text)
to authenticated;
-- The app state calls blocked_list as the signed-in person.
-- end_sesh was replaced, so give back the right to call it.
revoke all on function public.end_sesh(uuid) from public, anon;
grant execute on function public.end_sesh(uuid) to authenticated;

do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('seshhon-purge-chat', '*/5 * * * *', 'select public.purge_chat()');
  end if;
end;
$$;

create or replace function public.api_state() returns jsonb
language sql stable security invoker set search_path = public as $$
  select jsonb_build_object(
    'now', now(),
    'night', public.night_of(),
    'me', (
      select jsonb_build_object(
        'id', p.id, 'name', p.name, 'invite_code', p.invite_code,
        'colour', coalesce((select s.colour::text from public.statuses s where s.user_id = p.id and s.colour <> 'off' and s.expires_at > now()), 'off'),
        'expires_at', (select s.expires_at from public.statuses s where s.user_id = p.id and s.colour <> 'off' and s.expires_at > now())
      )
      from public.profiles p where p.id = auth.uid()
    ),
    'friends', coalesce((
      select jsonb_agg(
        jsonb_build_object('friendship', f.id, 'id', p.id, 'name', p.name, 'colour', coalesce(s.colour::text, 'off'), 'since', s.updated_at)
        order by case coalesce(s.colour::text, 'off') when 'on' then 0 when 'thinking' then 1 else 2 end, p.name
      )
      from public.friendships f
      join public.profiles p on p.id = case when f.requester = auth.uid() then f.addressee else f.requester end
      left join public.statuses s on s.user_id = p.id
      where f.state = 'accepted'
    ), '[]'::jsonb),
    'requests_in', coalesce((
      select jsonb_agg(jsonb_build_object('friendship', f.id, 'name', p.name) order by f.created_at)
      from public.friendships f join public.profiles p on p.id = f.requester
      where f.state = 'requested' and f.addressee = auth.uid()
    ), '[]'::jsonb),
    'requests_out', coalesce((
      select jsonb_agg(jsonb_build_object('friendship', f.id, 'name', p.name) order by f.created_at)
      from public.friendships f join public.profiles p on p.id = f.addressee
      where f.state = 'requested' and f.requester = auth.uid()
    ), '[]'::jsonb),
    'seshes', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', s.id,
          'mine', s.creator = auth.uid(),
          'creator_name', (select p.name from public.profiles p where p.id = s.creator),
          'locked_venue', s.locked_venue,
          'am_member', public.is_sesh_member(s.id, auth.uid()),
          'members', coalesce((
            select jsonb_agg(jsonb_build_object('id', m.user_id, 'name', p.name) order by m.joined_at)
            from public.sesh_members m left join public.profiles p on p.id = m.user_id
            where m.sesh_id = s.id
          ), '[]'::jsonb),
          'votes', coalesce((
            select jsonb_agg(jsonb_build_object('user_id', v.user_id, 'venue_id', v.venue_id, 'voted_at', v.voted_at))
            from public.venue_votes v where v.sesh_id = s.id
          ), '[]'::jsonb)
        )
        order by s.created_at desc
      )
      from public.seshes s
      where s.ended_at is null and s.created_at > now() - interval '8 hours'
    ), '[]'::jsonb),
    'venues', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', v.id, 'name', v.name, 'kind', v.kind, 'closes', v.closes, 'is_example', v.is_example,
          'average', (select r.average from public.venue_ratings r where r.venue_id = v.id),
          'ratings', coalesce((select r.ratings from public.venue_ratings r where r.venue_id = v.id), 0),
          'my_stars', coalesce((select r.stars from public.ratings r where r.venue_id = v.id and r.user_id = auth.uid()), 0),
          'my_tags', coalesce((select to_jsonb(r.tags) from public.ratings r where r.venue_id = v.id and r.user_id = auth.uid()), '[]'::jsonb)
        )
        order by v.name
      )
      from public.venues v
    ), '[]'::jsonb),
    'deals', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', d.id, 'venue_id', d.venue_id, 'type', d.type, 'title', d.title, 'is_alcohol', d.is_alcohol,
          'start_time', to_char(d.start_time, 'HH24:MI'), 'end_time', to_char(d.end_time, 'HH24:MI'),
          'running', public.deal_is_running(d),
          'used', coalesce(r.confirmed_at is not null, false),
          'code', case when r.confirmed_at is null and r.expires_at > now() then r.code end,
          'code_expires_at', case when r.confirmed_at is null and r.expires_at > now() then r.expires_at end
        )
        order by d.start_time, d.title
      )
      from public.deals d
      left join public.redemptions r on r.deal_id = d.id and r.user_id = auth.uid() and r.night = public.night_of()
      where d.active
    ), '[]'::jsonb),
    'staff_venues', coalesce((
      select jsonb_agg(vs.venue_id) from public.venue_staff vs where vs.user_id = auth.uid()
    ), '[]'::jsonb),
    'blocked', public.blocked_list()
  );
$$;

-- Tell the API about the new functions straight away.
notify pgrst, 'reload schema';
