#!/usr/bin/env bash
# Rebuilds supabase/setup.sql (the one file pasted into the Supabase SQL editor).
cd "$(dirname "$0")/../.."
{ echo "-- Seshhon database setup. Paste this whole file into the Supabase SQL editor and press Run."
  echo "-- Run it once on a new project. (Generated by tools/live/build-setup.sh from supabase/migrations and supabase/examples.sql.)"
  for f in supabase/migrations/*.sql supabase/examples.sql; do echo; echo "-- ======================= $(basename "$f")"; cat "$f"; done
} > supabase/setup.sql
