#!/usr/bin/env bash
# Rebuilds supabase/setup.sql (the one file pasted into the Supabase SQL editor on a new project)
# and supabase/update.sql (for a project set up before the age gate: migrations 0003 onwards).
cd "$(dirname "$0")/../.."
{ echo "-- Seshhon database setup. Paste this whole file into the Supabase SQL editor and press Run."
  echo "-- Run it once on a new project. (Generated by tools/live/build-setup.sh from supabase/migrations and supabase/examples.sql.)"
  for f in supabase/migrations/*.sql supabase/examples.sql; do echo; echo "-- ======================= $(basename "$f")"; cat "$f"; done
  echo; echo "notify pgrst, 'reload schema';"
} > supabase/setup.sql
{ echo "-- Seshhon database update. Paste this whole file into the Supabase SQL editor and press Run."
  echo "-- Use it on a project that was set up before the age gate (sign up says it cannot find"
  echo "-- public.api_sign_up(p_birth_date, p_name)). Run it once; do not use it on a new project, use setup.sql there."
  echo "-- (Generated by tools/live/build-setup.sh from supabase/migrations 0003 onwards.)"
  for f in supabase/migrations/*.sql; do
    case "$(basename "$f")" in 0001_*|0002_*) continue;; esac
    echo; echo "-- ======================= $(basename "$f")"; cat "$f"
  done
  echo; echo "-- Tell the API about the new functions straight away."
  echo "notify pgrst, 'reload schema';"
} > supabase/update.sql
