// Builds supabase/venues/perth-osm.sql: every named bar, pub, nightclub, beer garden and live music venue
// in greater Perth from OpenStreetMap, ready to paste into the Supabase SQL editor.
// Run: node tools/venues/import-osm.mjs            (downloads from the Overpass API)
//      node tools/venues/import-osm.mjs file.json  (uses an Overpass answer saved earlier)
// Data © OpenStreetMap contributors, under the Open Database Licence. The map already shows the credit.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '../..');
const OUT = path.join(root, 'supabase/venues/perth-osm.sql');
// Greater Perth: Two Rocks in the north, Rockingham in the south, the coast in the west, the hills in the east.
const BBOX = [-32.45, 115.6, -31.5, 116.15];   // south, west, north, east
const KINDS = { bar: 'Bar', pub: 'Pub', nightclub: 'Nightclub', biergarten: 'Beer garden', music_venue: 'Live music venue' };
const QUERY = `[out:json][timeout:120];nwr["amenity"~"^(${Object.keys(KINDS).join('|')})$"]["name"](${BBOX.join(',')});out center tags;`;
const SERVERS = ['https://overpass-api.de/api/interpreter', 'https://overpass.kumi.systems/api/interpreter'];

async function download() {
  for (const url of SERVERS) {
    try {
      const res = await fetch(url, { method: 'POST', body: new URLSearchParams({ data: QUERY }), headers: { 'User-Agent': 'SeshOn venue import (github.com/skylark18756333/Seshhon)' } });
      if (res.ok) return await res.json();
      console.error(url + ' answered ' + res.status);
    } catch (e) { console.error(url + ' failed: ' + e.message); }
  }
  throw new Error('Could not reach OpenStreetMap. Try again later.');
}

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const clean = (s, max) => String(s || '').replace(/\s+/g, ' ').trim().slice(0, max);

export function toRows(data) {
  const rows = new Map();
  for (const el of data.elements || []) {
    const t = el.tags || {};
    const lat = el.lat ?? el.center?.lat, lng = el.lon ?? el.center?.lon;
    const name = clean(t.name, 80);
    if (!name || !KINDS[t.amenity] || typeof lat !== 'number' || typeof lng !== 'number') continue;
    if (lat < BBOX[0] || lat > BBOX[2] || lng < BBOX[1] || lng > BBOX[3]) continue;
    const kind = t.amenity === 'bar' && t.cocktails === 'yes' ? 'Cocktail bar' : KINDS[t.amenity];
    rows.set(el.type + '/' + el.id, { osm: el.type + '/' + el.id, name, kind, lat: +lat.toFixed(6), lng: +lng.toFixed(6) });
  }
  return [...rows.values()].sort((a, b) => a.name.localeCompare(b.name) || a.osm.localeCompare(b.osm));
}

export function toSql(rows, when) {
  const lines = [
    '-- Greater Perth venues from OpenStreetMap (' + rows.length + ' venues, downloaded ' + when + ').',
    '-- Paste this whole file into the Supabase SQL editor and press Run. Running it again with a newer copy',
    '-- updates names and positions; it never deletes venues and never touches venues added by hand.',
    '-- Data © OpenStreetMap contributors, Open Database Licence (openstreetmap.org/copyright).',
    '-- (Generated by tools/venues/import-osm.mjs. Do not edit by hand.)',
    '',
    'alter table public.venues add column if not exists osm_id text;',
    'create unique index if not exists venues_osm_id_key on public.venues (osm_id);',
    ''
  ];
  if (rows.length) {
    lines.push('insert into public.venues (osm_id, name, kind, lat, lng) values');
    lines.push(rows.map((r) => '  (' + [q(r.osm), q(r.name), q(r.kind), r.lat, r.lng].join(', ') + ')').join(',\n'));
    lines.push('on conflict (osm_id) do update set name = excluded.name, kind = excluded.kind, lat = excluded.lat, lng = excluded.lng;');
  }
  lines.push('', "notify pgrst, 'reload schema';", '');
  return lines.join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const src = process.argv[2];
  const data = src ? JSON.parse(fs.readFileSync(src, 'utf8')) : await download();
  const rows = toRows(data);
  if (!src && rows.length < 50) throw new Error('Only ' + rows.length + ' venues came back, which looks wrong. Nothing was written.');
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, toSql(rows, new Date().toISOString().slice(0, 10)));
  console.log('Wrote ' + rows.length + ' venues to ' + path.relative(root, OUT));
}
